name: Terraform Deploy Prod

on:
  push:
    branches:
      - main
      - "release/v**"

  pull_request:
    branches:
      - main
      - "release/v**"

permissions:
  id-token: write
  contents: read

jobs:
  terraform-plan-prod:
    if: github.ref == 'refs/heads/main'
    name: Plan prod
    uses: Um4r-Arafath/tf-test/.github/workflows/deploy.yml@main
    with:
      aws-region: ap-southeast-1
      role-to-assume: arn:aws:iam::637423543671:role/tf-test
      backend-config: environments/prod/config.s3.tfbackend
      args: -var-file="environments/prod/terraform.tfvars"
      working-directory: ./services/api/iac
      deploy: false

  terraform-apply-prod:
    if: github.ref == 'refs/heads/release/v**'
    name: Deploy prod
    uses: Um4r-Arafath/tf-test/.github/workflows/deploy.yml@main
    with:
      aws-region: ap-southeast
      role-to-assume: arn:aws:iam::637423543671:role/tf-test
      backend-config: environments/prod/config.s3.tfbackend
      args: -var-file="environments/prod/terraform.tfvars"
      working-directory: ./services/api/iac
      deploy: true
